### ISSUE TITLE
PrismicPreview failing typescript checks.

### ISSUE THREAD

**Issue by bitscraps** [prismicio/prismic-next#99]
When upgrading from @prismicio/next 1.6.0 to 1.7.1 I now get the following typescript error when using PrismicPreview. 

```
pages/_app.tsx:82:20 - error TS2786: 'PrismicPreview' cannot be used as a JSX component.
  Its return type 'Element | Promise<Element>' is not a valid JSX element.
    Type 'Promise<Element>' is missing the following properties from type 'ReactElement<any, any>': type, props, key

                  <PrismicPreview repositoryName={repositoryName} />
```

This is using the next pages folder versus using nexts new app folder.

### Versions

- `@prismicio/next`: 1.7.1
